spring:
  application:
    name: hms-api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: room-service
            uri: lb://ROOM-SERVICE
            predicates:
              - path=/room/**
#Booking Service
#          - id: room-service
#            uri: lb://ROOM-SERVICE
#            predicates:
#              - path=/room/**

#Customer Services
#          - id: room-service
#            uri: lb://ROOM-SERVICE
#            predicates:
#              - path=/room/**
server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
